### ISSUE TITLE
As a developer I want to change the follow and likes lists to hash-sets, for faster iteration.

### ISSUE THREAD

**Issue by mortfb** [ITU-BDSA2024-GROUP15/Chirp#117]
As a developer I want to change the follow and likes lists to hash-sets, for faster iteration.

Finished criteria:
When the follow and likes lists are changed to hash-sets
When pushed to main

**Comment by Powsdaws** [comment]
Leets keep the current methods so we un IN query in the database to check whenever a an author is in the follow and like lists
