### ISSUE TITLE
(1.b) As a developer I want to add new functionality to our CheepRepository, in order to facilitate adding cheeps

### ISSUE THREAD

**Issue by VernesNemo** [ITU-BDSA2024-GROUP15/Chirp#38]
Acceptance criteria:
After the rework we should be able to:
- Find Author by name
- Find Author by email
- Create a new Author
- Create a new cheep (and a respective author if one does not exist yet).

Done when pushed to main

**Comment by Powsdaws** [comment]
Made initial functionality. Have not been tested check branch "Adding_cheeps"
