### ISSUE TITLE
As a developer i want to test make end to end test for sending cheeps using Playwright, such that we can verify that all of our components in the system can run together

### ISSUE THREAD

**Issue by Powsdaws** [ITU-BDSA2024-GROUP15/Chirp#62]
As a developer i want to test make end to end test for sending cheeps using Playwright, such that we can verify that all of our components in the system can run together

Acceptence Criteria:
- When we have an e2e for sending a new cheep
- Checking that the send cheep box only appears when logged in
- When we have an e2e test for testing if a user gets an error messages when sending a cheep longer than 160 characters

**Comment by SukiNekoo** [comment]
- Checking that the send cheep box only appears when logged in
- When we have an e2e test for testing if a user gets an error messages when sending a cheep longer than 160 characters
