### ISSUE TITLE
As a user, I want to be able to use special characters (&<") in my cheeps

### ISSUE THREAD

**Issue by VernesNemo** [ITU-BDSA2024-GROUP15/Chirp#7]
As a user, I want to be able to use special characters (&<") in my cheeps. Currently the program either doesnt run, or doesnt include the characters in the cheep, such as "cheep" becoming cheep.

Acceptance criteria:
Special characters can be included in cheeps and be stored correctly in the database

**Comment by KassandraW** [comment]
omg can't wait for this (๑>ᴗ<๑)  ٩(^ᗜ^ )و ´-
